<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shanti-Windows-Laptop" failures="0" tests="3" name="org.techArk.tests.CRUD.ValidateUpdateData_Functionality" time="13.591" errors="1" timestamp="2024-03-19T09:04:31 PDT" skipped="1">
  <testcase classname="org.techArk.tests.CRUD.ValidateUpdateData_Functionality" name="validateUpdateDataFunctionality" time="0.000">
    <skipped/>
  </testcase> <!-- validateUpdateDataFunctionality -->
  <system-out/>
  <testcase classname="org.techArk.tests.CRUD.ValidateUpdateData_Functionality" name="validateAddDataFunctionality" time="0.761"/>
  <system-out/>
  <testcase classname="org.techArk.tests.CRUD.ValidateUpdateData_Functionality" name="validateAddedDataInGetData" time="12.830">
    <error message="Cannot invoke &quot;org.techArk.responsePOJO.GetDataResponse.getId()&quot; because &quot;getDataResponse&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.techArk.responsePOJO.GetDataResponse.getId()" because "getDataResponse" is null
at org.techArk.tests.CRUD.ValidateUpdateData_Functionality.validateAddedDataInGetData(ValidateUpdateData_Functionality.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateAddedDataInGetData -->
  <system-out/>
</testsuite> <!-- org.techArk.tests.CRUD.ValidateUpdateData_Functionality -->
